project_id_for_st2-frontend-chart:
  image:
    repository: artifactory.dagility.com/docker/project_id_for_st2-frontend
    tag: latest
    pullPolicy: Always
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx-internal
    hosts:
    - host: project_id_for_st2-frontend-default.dagility.com
      paths:
      - /
  serviceAccount:
    create: false

project_id_for_st2-backend-chart:
  image:
    repository: artifactory.dagility.com/docker/project_id_for_st2-backend
    tag: latest
    pullPolicy: Always
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx-internal
    hosts:
    - host: project_id_for_st2-backend-default.dagility.com
      paths:
      - /
  serviceAccount:
    create: false
